theme = "hyde"
baseURL = "https://nju-cvicse.cn/"
defaultContentLanguage = "zh-cn"
title = "NJU-CVICSE"

[languages.zh-cn]
  languageCode = "zh-cn"


[params]
  themeColor = "theme-base-0d"
  description = "南京大学-中创软件联合研究中心"